package com.medicare.identity.entity;

public enum AuditEventType {

    ACCOUNT_CREATED,
    SYSTEM_BOOTSTRAP_ADMIN_CREATED,
    ACCOUNT_ACTIVATED,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGIN_LOCKOUT_TRIGGERED,
    LOGIN_LOCKOUT_CLEARED,
    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    ACCOUNT_SUSPENDED,
    ACCOUNT_REACTIVATED,
    ACCOUNT_DEACTIVATED,
    ACCOUNT_REACTIVATED_FROM_DEACTIVATED,
    ROLE_CHANGED,
    LOGOUT,
    PATIENT_PROVISIONING_CONFLICT,
    TOKEN_REVOKED
}
